### ISSUE TITLE
Hitting back button while on CK docs page loads raw html of the page 

### ISSUE THREAD

**Issue by illizona** [RadiusNetworks/campaignkit-documentation#13]
First visit to https://campaignkit.radiusnetworks.com/docs/overview loads correctly as expected.  
<img width="1216" alt="screen shot 2016-04-04 at 11 35 45 pm" src="https://cloud.githubusercontent.com/assets/7259851/14271380/3151a352-fabe-11e5-9905-c175337e6da2.png">

Clicking on any link on the page (I clicked on Android JavaDocs) and then hitting the back button loads the raw html for the page.

<img width="1249" alt="screen shot 2016-04-04 at 11 35 55 pm" src="https://cloud.githubusercontent.com/assets/7259851/14271383/37209414-fabe-11e5-8c34-696c889aa9fa.png">

**Comment by cupakromer** [comment]
@illizona I cannot reproduce this. What web browser and version were you using? Can you consistently repo this?
