### ISSUE TITLE
Spelling & Typos

### ISSUE THREAD

**Issue by csexton** [RadiusNetworks/campaignkit-documentation#14]
![image](https://cloud.githubusercontent.com/assets/16963/20404037/2de7bc54-acd1-11e6-8a65-09c820141f84.png)

Found by @kennygmc. @AT89 would you mind taking a crack at this?

**Comment by ajhewitt** [comment]
That looks like my horrible spelling 😿  It started life in `gossamer/app/views/help`. I'm not sure if we use/need that anymore. If so then it needs to get fixed [here](https://github.com/RadiusNetworks/gossamer/blame/master/app/views/help/_contents.html.slim) as well.
