### ISSUE TITLE
Campaign Kit docs linked to older binaries

### ISSUE THREAD

**Issue by illizona** [RadiusNetworks/campaignkit-documentation#6]
http://developer.radiusnetworks.com/campaignkit/ links refer to older binaries.

For instance the Android Studio link points to https://s3.amazonaws.com/campaignkit-android/campaignkit-android-0.0.2.aar instead of v0.4.0.

**Comment by csexton** [comment]
That was a stale page, I replaced it with a redirect to the actual documentation. Luckily that will point folks to the proper download page on github releases.

Related:
https://github.com/RadiusNetworks/campaignkit-android/releases/tag/0.4.1
